name: Sync Substack → Markdown

on:
  schedule:
    # Check once a day at 09:00 UTC.  Adjust to taste.
    - cron:  '0 9 * * *'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert feed items to Markdown
        uses: keiranlovett/rss-feed-to-markdown@v1.1.6
        with:
          feed_url: 'https://valpetal.substack.com/feed'
          template_file: 'assets/substack-template.md'
          output_dir: 'posts'
          max_posts: 10

      - name: Commit & push if anything changed
        run: |
          git config user.name  "substack-bot"
          git config user.email "actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync new Substack issue"
            git push
          fi
